/**
 * sampleData.js
 *
 * Seed data for the Uniblox demo environment. All arrays and objects here are
 * imported into useAppStore as the initial state, making the app fully functional
 * without a backend connection.
 *
 * In production, replace these static imports with async API calls on mount
 * (e.g., using React Query or SWR) that populate the same Zustand store keys.
 *
 * Exports:
 *  carriers    — array of carrier configuration objects
 *  submissions — array of group insurance submission objects
 *  eois        — array of Evidence of Insurability request objects
 *  enrollments — array of active group enrollment objects
 *  auditLog    — array of audit trail entry objects
 *  stateRules  — map of state code → regulatory rule object
 *
 *  getStateRules(state) — helper that returns the rule object for a given
 *                         2-letter state code, falling back to a safe default
 *                         if the state is not in the map (to prevent null errors
 *                         in compliance.js)
 *
 * Data shape notes:
 *  - carrier.industryAppetite values: 'ACCEPT' | 'MARGINAL' | 'DECLINE'
 *    (compliance.js normalizes these to 'ACCEPTABLE' | 'MARGINAL' | 'OUTSIDE_APPETITE')
 *  - submission.status values: 'PENDING' | 'PROCESSING' | 'REFERRED' | 'APPROVED' | 'DECLINED'
 *  - submission.recommendation values: 'APPROVE' | 'REFER' | 'DECLINE' (AI output)
 *  - eoi.status values: 'PENDING' | 'APPROVED' | 'DECLINED' | 'IN_REVIEW' | 'PENDING_INFO'
 *  - stateRules keys: 2-letter US state codes; values contain regulatory thresholds,
 *    prohibited risk factors, and adverse action deadlines
 */

// ─── Carriers ────────────────────────────────────────────────────────────────
export const carriers = [
  {
    id: 'carrier_001',
    name: 'Acme Life & Benefits',
    legalName: 'Acme Life and Benefits Insurance Company',
    naicNumber: '71234',
    status: 'Active',
    contractStart: '2021-01-01',
    primaryContact: 'Jennifer Walsh',
    submissionCount: 89,
    // Appetite by industry
    industryAppetite: {
      Technology:             'ACCEPT',
      Healthcare:             'ACCEPT',
      'Professional Services':'ACCEPT',
      Finance:                'ACCEPT',
      Education:              'ACCEPT',
      Nonprofit:              'ACCEPT',
      Legal:                  'ACCEPT',
      Retail:                 'MARGINAL',
      Manufacturing:          'MARGINAL',
      Transportation:         'MARGINAL',
      Hospitality:            'MARGINAL',
      'Real Estate':          'MARGINAL',
      Energy:                 'MARGINAL',
      Restaurant:             'DECLINE',
      Construction:           'DECLINE',
      Agriculture:            'DECLINE',
      'Food Service':         'DECLINE',
    },
    // GI limits by coverage type
    giLimits: {
      Life:       50000,
      Health:     null, // state-dependent
      Disability: 6000,  // monthly
      Dental:     2000,  // annual
      Vision:     500,   // annual
      LTC:        3000,  // monthly
    },
    maxGroupSize: { Construction: 0, Restaurant: 0, Agriculture: 0 },
    autoApproveThreshold: 35,
    autoDeclineThreshold: 75,
    confidenceMinimum: 80,
    states: 'ALL',
    customRules: `Do not approve any restaurant group with alcohol service and fewer than 5 years of operation.
Flag all construction companies with more than 10 employees for manual review.
Healthcare groups over 200 employees require senior underwriter sign-off.
Technology startups under 2 years of operation require additional financial documentation.
Any group with more than 3 claims in the prior 2 years exceeding $50,000 total must be referred to senior underwriter.`,
  },
  {
    id: 'carrier_002',
    name: 'Meridian Group Insurance',
    legalName: 'Meridian Group Insurance Corporation',
    naicNumber: '83456',
    status: 'Active',
    contractStart: '2022-06-01',
    primaryContact: 'David Kim',
    submissionCount: 34,
    industryAppetite: {
      Technology:             'ACCEPT',
      Finance:                'ACCEPT',
      'Professional Services':'ACCEPT',
      Education:              'ACCEPT',
      Healthcare:             'MARGINAL',
      Retail:                 'MARGINAL',
      Manufacturing:          'MARGINAL',
      Nonprofit:              'MARGINAL',
      Restaurant:             'DECLINE',
      Construction:           'DECLINE',
      Agriculture:            'DECLINE',
      Transportation:         'DECLINE',
      Hospitality:            'DECLINE',
    },
    giLimits: {
      Life: 40000, Health: null, Disability: 5000, Dental: 1500, Vision: 400, LTC: 2500,
    },
    autoApproveThreshold: 25,
    autoDeclineThreshold: 70,
    confidenceMinimum: 85,
    states: ['CA','TX','FL','NY','IL','WA','MA','NJ','PA','GA','CO','AZ','NV','OR','UT',
             'VA','NC','MD','MN','WI','MO','TN','IN','OH','MI','KY','LA','AL','SC','CT'],
    customRules: `More conservative appetite. Technology companies must have at least 18 months of operating history.
Finance companies must provide latest audited financials. Healthcare groups must provide credentialing documentation.`,
  },
  {
    id: 'carrier_003',
    name: 'Pacific Coast Benefits',
    legalName: 'Pacific Coast Benefits Insurance Inc.',
    naicNumber: '92167',
    status: 'Active',
    contractStart: '2023-03-15',
    primaryContact: 'Lisa Yamamoto',
    submissionCount: 4, // cold start: under 50
    industryAppetite: {
      Technology:   'ACCEPT',
      Healthcare:   'ACCEPT',
      Finance:      'ACCEPT',
      Retail:       'ACCEPT',
      Hospitality:  'ACCEPT',
      Manufacturing:'MARGINAL',
      Transportation:'MARGINAL',
      Agriculture:  'MARGINAL',
      Construction: 'DECLINE',
      Restaurant:   'MARGINAL',
    },
    giLimits: {
      Life: 75000, Health: null, Disability: 8000, Dental: 2500, Vision: 600, LTC: 4000,
    },
    autoApproveThreshold: 40,
    autoDeclineThreshold: 80,
    confidenceMinimum: 75,
    states: ['CA','OR','WA','NV','AZ','UT','CO','ID','MT','WY','HI','AK'],
    customRules: `West Coast focus. California submissions require additional compliance review.
Tech companies in Bay Area receive expedited processing. Hospitality groups must provide last 3 years of revenue.`,
  },
]

// ─── Submissions ─────────────────────────────────────────────────────────────
export const submissions = [
  {
    id: 'SUB-2024-001',
    employerName: 'Riverside Restaurant Group',
    industry: 'Restaurant',
    state: 'IL',
    employeeCount: 45,
    annualRevenue: '$2.1M',
    yearsInBusiness: 4,
    businessEntityType: 'LLC',
    coverageTypes: ['Life', 'Health', 'Disability'],
    requestedEffectiveDate: '2024-03-01',
    brokerName: 'Marcus Thompson',
    brokerLicense: 'IL-BRK-44821',
    brokerEmail: 'mthompson@brokergroup.com',
    brokerPhone: '(312) 555-0182',
    submittedAt: '2024-01-15T09:23:00Z',
    status: 'DECLINED',
    priority: 'high',
    assignedUnderwriter: 'Sarah Chen',
    carrierId: 'carrier_001',
    riskScore: 72,
    confidenceLevel: 82,
    recommendation: 'DECLINE',
    carrierAppetiteMatch: 'OUTSIDE_APPETITE',
    priorClaims: true,
    claimsCount: 3,
    claimsTotal: '$127,000',
    largestClaim: '$58,000',
    claimsDescription: 'Workers compensation claims related to kitchen injuries and slip/falls.',
    selfFunded: false,
    adverseActionDeadline: '2024-01-20T09:23:00Z',
    adverseActionSent: false,
    subScores: { liabilityRisk: 78, financialStability: 65, claimsHistory: 72, industryRisk: 80 },
    dataCompleteness: 0.82,
    reasoning: [
      'Restaurant industry presents elevated liability exposure due to food service, alcohol service, and high employee turnover.',
      'Prior claims history of 3 workers compensation claims totaling $127,000 in last 2 years significantly elevates risk profile.',
      'Annual revenue of $2.1M for 45 employees suggests thin margins (≈$46K/employee), indicating financial fragility.',
      'Carrier appetite policy explicitly excludes restaurant groups with alcohol service under 5 years of operation — 4 years does not meet threshold.',
      'IL adverse action notice required within 5 days per 215 ILCS 5/357.10.',
    ],
    missingInfoFlags: ['Tax returns for past 2 years', 'Loss runs from prior carrier', 'Liquor liability coverage details'],
    suggestedNextSteps: ['Generate adverse action notice', 'Start 5-day IL compliance timer', 'Log decision in audit trail'],
    complianceNotes: ['IL adverse action notice required within 5 business days', 'IL DOI standard form required for groups over 50 — N/A here'],
    stateOverride: null,
    additionalRiskFactors: ['Full bar service', 'High turnover industry', 'Seasonal revenue fluctuation'],
    messages: [
      { id: 1, from: 'underwriter', sender: 'Sarah Chen', text: 'Reviewing submission — requesting loss runs from prior carrier before finalizing.', timestamp: '2024-01-15T10:15:00Z' },
      { id: 2, from: 'broker', sender: 'Marcus Thompson', text: 'Will get those loss runs to you by end of day. Note the client is a well-established group in River North.', timestamp: '2024-01-15T10:45:00Z' },
      { id: 3, from: 'underwriter', sender: 'Sarah Chen', text: 'Loss runs received. Proceeding with assessment. The prior claims pattern is a concern.', timestamp: '2024-01-15T16:30:00Z' },
    ],
    documents: [
      { id: 'd1', name: 'Riverside_Application.pdf', size: '2.4 MB', uploadedBy: 'Marcus Thompson', uploadedAt: '2024-01-15T09:23:00Z', status: 'Reviewed', type: 'pdf' },
      { id: 'd2', name: 'Loss_Runs_2022_2023.pdf',   size: '1.1 MB', uploadedBy: 'Marcus Thompson', uploadedAt: '2024-01-15T16:00:00Z', status: 'Reviewed', type: 'pdf' },
    ],
  },
  {
    id: 'SUB-2024-002',
    employerName: 'TechNova Solutions',
    industry: 'Technology',
    state: 'TX',
    employeeCount: 127,
    annualRevenue: '$8.5M',
    yearsInBusiness: 7,
    businessEntityType: 'Corporation',
    coverageTypes: ['Life', 'Health', 'Dental', 'Vision'],
    requestedEffectiveDate: '2024-02-01',
    brokerName: 'Angela Rodriguez',
    brokerLicense: 'TX-BRK-98231',
    brokerEmail: 'arodriguez@benefitsplus.com',
    brokerPhone: '(512) 555-0247',
    submittedAt: '2024-01-14T14:05:00Z',
    status: 'APPROVED',
    priority: 'low',
    assignedUnderwriter: 'John Doe',
    carrierId: 'carrier_001',
    riskScore: 28,
    confidenceLevel: 91,
    recommendation: 'APPROVE',
    carrierAppetiteMatch: 'ACCEPTABLE',
    priorClaims: false,
    selfFunded: false,
    adverseActionDeadline: null,
    adverseActionSent: null,
    subScores: { liabilityRisk: 22, financialStability: 30, claimsHistory: 10, industryRisk: 25 },
    dataCompleteness: 0.95,
    reasoning: [
      'Technology sector presents below-average liability exposure for this carrier appetite.',
      'No prior claims history across all requested coverage types.',
      'Revenue of $8.5M for 127 employees ($66.9K/employee) indicates solid financial position.',
      '7-year operating history demonstrates business stability.',
      'All requested coverage types fall within carrier GI limits.',
    ],
    missingInfoFlags: [],
    suggestedNextSteps: ['Generate quote', 'Send to carrier system', 'Notify broker of approval'],
    complianceNotes: ['TX no special adverse action requirements for approvals', 'Standard NAIC rules apply'],
    stateOverride: null,
    additionalRiskFactors: [],
    messages: [
      { id: 1, from: 'underwriter', sender: 'John Doe', text: 'Clean submission. Approving per AI recommendation.', timestamp: '2024-01-14T15:20:00Z' },
    ],
    documents: [
      { id: 'd3', name: 'TechNova_Application.pdf', size: '3.1 MB', uploadedBy: 'Angela Rodriguez', uploadedAt: '2024-01-14T14:05:00Z', status: 'Reviewed', type: 'pdf' },
      { id: 'd4', name: 'Census_TechNova.xlsx', size: '0.8 MB', uploadedBy: 'Angela Rodriguez', uploadedAt: '2024-01-14T14:06:00Z', status: 'Reviewed', type: 'xlsx' },
    ],
  },
  {
    id: 'SUB-2024-003',
    employerName: 'Great Lakes Manufacturing',
    industry: 'Manufacturing',
    state: 'OH',
    employeeCount: 89,
    annualRevenue: '$12.3M',
    yearsInBusiness: 22,
    businessEntityType: 'Corporation',
    coverageTypes: ['Life', 'Disability'],
    requestedEffectiveDate: '2024-03-15',
    brokerName: 'Robert Fielding',
    brokerLicense: 'OH-BRK-11294',
    brokerEmail: 'rfielding@midwestbenefits.com',
    brokerPhone: '(614) 555-0319',
    submittedAt: '2024-01-13T11:30:00Z',
    status: 'REFERRED',
    priority: 'medium',
    assignedUnderwriter: 'Sarah Chen',
    carrierId: 'carrier_001',
    riskScore: 55,
    confidenceLevel: 74,
    recommendation: 'REFER',
    carrierAppetiteMatch: 'MARGINAL',
    priorClaims: true,
    claimsCount: 2,
    claimsTotal: '$83,000',
    largestClaim: '$55,000',
    claimsDescription: 'Workers compensation: one machinery-related injury, one repetitive stress claim.',
    selfFunded: false,
    adverseActionDeadline: null,
    adverseActionSent: null,
    subScores: { liabilityRisk: 62, financialStability: 45, claimsHistory: 58, industryRisk: 60 },
    dataCompleteness: 0.78,
    reasoning: [
      'Manufacturing carries elevated workers compensation risk; 2 prior claims align with industry baseline.',
      'OSHA compliance documentation not provided — needed to complete risk assessment.',
      'Revenue and employee count are consistent with a stable mid-size operation.',
      'Industry classified as MARGINAL by carrier — requires manual underwriter review.',
      'Confidence score of 74% above threshold but missing OSHA data warrants referral.',
    ],
    missingInfoFlags: ['OSHA compliance records last 3 years', 'Safety program documentation', 'Equipment maintenance logs'],
    suggestedNextSteps: ['Assign to senior underwriter', 'Request OSHA compliance documentation', 'Request safety program details'],
    complianceNotes: ['OH NAIC standard rules apply', 'No special adverse action requirements'],
    stateOverride: null,
    additionalRiskFactors: ['Heavy machinery operation', 'Physical labor workforce'],
    messages: [
      { id: 1, from: 'underwriter', sender: 'Sarah Chen', text: 'Referring for additional documentation. Need OSHA records before we can approve.', timestamp: '2024-01-13T14:00:00Z' },
      { id: 2, from: 'broker', sender: 'Robert Fielding', text: 'I\'ll reach out to the client for OSHA docs. Should have them within 3 business days.', timestamp: '2024-01-13T15:22:00Z' },
    ],
    documents: [
      { id: 'd5', name: 'GreatLakes_App.pdf', size: '2.8 MB', uploadedBy: 'Robert Fielding', uploadedAt: '2024-01-13T11:30:00Z', status: 'Reviewed', type: 'pdf' },
    ],
  },
  {
    id: 'SUB-2024-004',
    employerName: 'Midtown Medical Partners',
    industry: 'Healthcare',
    state: 'NY',
    employeeCount: 23,
    annualRevenue: '$4.2M',
    yearsInBusiness: 11,
    businessEntityType: 'Partnership',
    coverageTypes: ['Life', 'Health'],
    requestedEffectiveDate: '2024-02-15',
    brokerName: 'Christine Park',
    brokerLicense: 'NY-BRK-55671',
    brokerEmail: 'cpark@nycbenefits.com',
    brokerPhone: '(212) 555-0493',
    submittedAt: '2024-01-12T10:00:00Z',
    status: 'APPROVED',
    priority: 'low',
    assignedUnderwriter: 'John Doe',
    carrierId: 'carrier_001',
    riskScore: 31,
    confidenceLevel: 88,
    recommendation: 'APPROVE',
    carrierAppetiteMatch: 'ACCEPTABLE',
    priorClaims: false,
    selfFunded: false,
    adverseActionDeadline: null,
    adverseActionSent: null,
    subScores: { liabilityRisk: 28, financialStability: 32, claimsHistory: 5, industryRisk: 35 },
    dataCompleteness: 0.91,
    reasoning: [
      'Healthcare group of 23 employees qualifies as small group under NY law — guaranteed issue applies.',
      'No prior claims history; clean risk profile.',
      'Medical partnership with 11 years of operation demonstrates strong stability.',
      'Pure community rating required for NY small groups — pricing compliant.',
      'NY small group: 1-100 employees, guaranteed issue, pure community rating (NY Insurance Law Article 43).',
    ],
    missingInfoFlags: ['Credentialing documentation for practitioners'],
    suggestedNextSteps: ['Generate quote', 'Apply NY community rating', 'Notify broker of approval'],
    complianceNotes: ['NY small group rules apply — guaranteed issue', 'Pure community rating required', 'Adverse action notice within 3 business days if declined (N/A)'],
    stateOverride: null,
    additionalRiskFactors: [],
    messages: [],
    documents: [
      { id: 'd6', name: 'MidtownMedical_App.pdf', size: '1.9 MB', uploadedBy: 'Christine Park', uploadedAt: '2024-01-12T10:00:00Z', status: 'Reviewed', type: 'pdf' },
    ],
  },
  {
    id: 'SUB-2024-005',
    employerName: 'Sunrise Home Health',
    industry: 'Healthcare',
    state: 'CA',
    employeeCount: 156,
    annualRevenue: '$18.7M',
    yearsInBusiness: 9,
    businessEntityType: 'Corporation',
    coverageTypes: ['Life', 'Health', 'LTC'],
    requestedEffectiveDate: '2024-04-01',
    brokerName: 'Patricia Nguyen',
    brokerLicense: 'CA-BRK-78923',
    brokerEmail: 'pnguyen@sunbenefits.com',
    brokerPhone: '(415) 555-0612',
    submittedAt: '2024-01-11T16:45:00Z',
    status: 'REFERRED',
    priority: 'medium',
    assignedUnderwriter: null,
    carrierId: 'carrier_001',
    riskScore: 44,
    confidenceLevel: 58, // LOW CONFIDENCE — triggers mandatory human review
    recommendation: 'REFER',
    carrierAppetiteMatch: 'ACCEPTABLE',
    priorClaims: true,
    claimsCount: 1,
    claimsTotal: '$22,000',
    largestClaim: '$22,000',
    claimsDescription: 'One FMLA-related disability claim.',
    selfFunded: false,
    lowConfidenceFlag: true,
    adverseActionDeadline: null,
    adverseActionSent: null,
    subScores: { liabilityRisk: 48, financialStability: 40, claimsHistory: 30, industryRisk: 50 },
    dataCompleteness: 0.65,
    reasoning: [
      'Home health sector carries elevated professional liability risk but is acceptable to carrier.',
      'CA large group (101+ employees): experience rating permitted, medical underwriting allowed.',
      'Submission lacks key financial data (prior year tax returns, loss runs) reducing confidence.',
      'LOW CONFIDENCE (58%) — insufficient data for confident automated decision. Mandatory human review.',
      'CA continuance offer may be required if policy is later nonrenewed.',
    ],
    missingInfoFlags: ['Prior 2 years tax returns', 'Loss runs from previous carrier', 'Employee roster with job titles', 'CA DLSR compliance documentation'],
    suggestedNextSteps: ['Assign to senior underwriter', 'Request financial documentation', 'Request loss runs'],
    complianceNotes: ['CA large group rules apply', 'CA Insurance Code § 10700-10755', 'Continuance offer required if policy cancelled or nonrenewed'],
    stateOverride: null,
    additionalRiskFactors: ['Home health — in-patient/caregiver risk', 'FMLA exposure'],
    messages: [],
    documents: [],
  },
  {
    id: 'SUB-2024-006',
    employerName: 'Premier Legal Group',
    industry: 'Legal',
    state: 'TX',
    employeeCount: 18,
    annualRevenue: '$3.1M',
    yearsInBusiness: 15,
    businessEntityType: 'LLC',
    coverageTypes: ['Life', 'Health', 'Disability'],
    requestedEffectiveDate: '2024-02-01',
    brokerName: 'Angela Rodriguez',
    brokerLicense: 'TX-BRK-98231',
    brokerEmail: 'arodriguez@benefitsplus.com',
    brokerPhone: '(512) 555-0247',
    submittedAt: '2024-01-10T09:15:00Z',
    status: 'APPROVED',
    priority: 'low',
    assignedUnderwriter: 'John Doe',
    carrierId: 'carrier_001',
    riskScore: 22,
    confidenceLevel: 93,
    recommendation: 'APPROVE',
    carrierAppetiteMatch: 'ACCEPTABLE',
    priorClaims: false,
    selfFunded: false,
    adverseActionDeadline: null,
    adverseActionSent: null,
    subScores: { liabilityRisk: 18, financialStability: 25, claimsHistory: 5, industryRisk: 20 },
    dataCompleteness: 0.94,
    reasoning: [
      'Legal/Professional Services is a preferred industry for this carrier.',
      'No prior claims history across all requested coverage types.',
      '$3.1M revenue for 18 employees ($172K/employee) indicates a high-value professional firm.',
      '15 years of operation demonstrates exceptional stability and low churn risk.',
      'All coverage types well within GI limits.',
    ],
    missingInfoFlags: [],
    suggestedNextSteps: ['Generate quote', 'Send to carrier system', 'Notify broker of approval'],
    complianceNotes: ['TX standard NAIC rules', 'No special requirements for professional services'],
    stateOverride: null,
    additionalRiskFactors: [],
    messages: [],
    documents: [
      { id: 'd7', name: 'PremierLegal_App.pdf', size: '1.7 MB', uploadedBy: 'Angela Rodriguez', uploadedAt: '2024-01-10T09:15:00Z', status: 'Reviewed', type: 'pdf' },
    ],
  },
  {
    id: 'SUB-2024-007',
    employerName: 'Metro Construction LLC',
    industry: 'Construction',
    state: 'CO',
    employeeCount: 67,
    annualRevenue: '$9.4M',
    yearsInBusiness: 12,
    businessEntityType: 'LLC',
    coverageTypes: ['Life', 'Disability'],
    requestedEffectiveDate: '2024-03-01',
    brokerName: 'James Ortega',
    brokerLicense: 'CO-BRK-23841',
    brokerEmail: 'jortega@rmbbenefits.com',
    brokerPhone: '(720) 555-0738',
    submittedAt: '2024-01-09T13:00:00Z',
    status: 'DECLINED',
    priority: 'high',
    assignedUnderwriter: 'Sarah Chen',
    carrierId: 'carrier_001',
    riskScore: 78,
    confidenceLevel: 88,
    recommendation: 'DECLINE',
    carrierAppetiteMatch: 'OUTSIDE_APPETITE',
    outsideAppetiteFlag: true,
    priorClaims: true,
    claimsCount: 5,
    claimsTotal: '$214,000',
    largestClaim: '$98,000',
    claimsDescription: 'Multiple workers compensation claims including one serious fall injury.',
    selfFunded: false,
    adverseActionDeadline: '2024-01-19T13:00:00Z',
    adverseActionSent: true,
    subScores: { liabilityRisk: 85, financialStability: 70, claimsHistory: 80, industryRisk: 88 },
    dataCompleteness: 0.88,
    reasoning: [
      'Construction industry is classified as DECLINE by Acme Life carrier appetite — immediate flag.',
      'High physical labor risk, elevated workers compensation exposure.',
      '5 prior claims totaling $214,000 in 2 years is significantly above threshold.',
      'Carrier appetite override: this case should not have been submitted to this carrier.',
    ],
    missingInfoFlags: [],
    suggestedNextSteps: ['Decline — outside carrier appetite', 'Generate adverse action notice', 'Suggest reassignment to a carrier that writes construction'],
    complianceNotes: ['CO NAIC standard adverse action rules', 'Notice sent 2024-01-19'],
    stateOverride: null,
    additionalRiskFactors: ['High-rise construction', 'Subcontractor exposure'],
    messages: [
      { id: 1, from: 'underwriter', sender: 'Sarah Chen', text: 'Declining — Construction is outside carrier appetite. Adverse action notice sent.', timestamp: '2024-01-09T14:30:00Z' },
    ],
    documents: [],
  },
  {
    id: 'SUB-2024-008',
    employerName: 'Pacific Northwest Retail',
    industry: 'Retail',
    state: 'WA',
    employeeCount: 234,
    annualRevenue: '$45M',
    yearsInBusiness: 28,
    businessEntityType: 'Corporation',
    coverageTypes: ['Life', 'Health', 'Dental'],
    requestedEffectiveDate: '2024-04-01',
    brokerName: 'Susan Kelley',
    brokerLicense: 'WA-BRK-66129',
    brokerEmail: 'skelley@pnwbenefits.com',
    brokerPhone: '(206) 555-0851',
    submittedAt: '2024-01-08T08:30:00Z',
    status: 'REFERRED',
    priority: 'medium',
    assignedUnderwriter: 'Sarah Chen',
    carrierId: 'carrier_001',
    riskScore: 47,
    confidenceLevel: 79,
    recommendation: 'REFER',
    carrierAppetiteMatch: 'MARGINAL',
    priorClaims: true,
    claimsCount: 2,
    claimsTotal: '$41,000',
    largestClaim: '$29,000',
    claimsDescription: 'One workers comp claim, one short-term disability claim.',
    selfFunded: false,
    adverseActionDeadline: null,
    adverseActionSent: null,
    subScores: { liabilityRisk: 50, financialStability: 38, claimsHistory: 40, industryRisk: 52 },
    dataCompleteness: 0.84,
    reasoning: [
      'Retail classified as MARGINAL — requires manual review per carrier guidelines.',
      'Large group (234 employees) warrants senior underwriter sign-off.',
      'WA state requires specific DOL&I compliance verification for large groups.',
      'Revenue/employee ratio ($192K) is healthy for retail sector.',
    ],
    missingInfoFlags: ['WA L&I compliance documentation', 'Benefits summary from prior carrier'],
    suggestedNextSteps: ['Assign to senior underwriter', 'Request WA L&I documentation', 'Review prior carrier experience'],
    complianceNotes: ['WA large group rules', 'WA Insurance Commissioner oversight'],
    stateOverride: null,
    additionalRiskFactors: ['High employee turnover (retail)', 'Multi-location operation'],
    messages: [],
    documents: [],
  },
  {
    id: 'SUB-2024-009',
    employerName: 'First Financial Advisors',
    industry: 'Finance',
    state: 'MA',
    employeeCount: 12,
    annualRevenue: '$1.8M',
    yearsInBusiness: 8,
    businessEntityType: 'LLC',
    coverageTypes: ['Life', 'Health'],
    requestedEffectiveDate: '2024-02-15',
    brokerName: 'Derek Walsh',
    brokerLicense: 'MA-BRK-33712',
    brokerEmail: 'dwalsh@newenglandbenefits.com',
    brokerPhone: '(617) 555-0924',
    submittedAt: '2024-01-07T11:00:00Z',
    status: 'APPROVED',
    priority: 'low',
    assignedUnderwriter: 'John Doe',
    carrierId: 'carrier_001',
    riskScore: 19,
    confidenceLevel: 95,
    recommendation: 'APPROVE',
    carrierAppetiteMatch: 'ACCEPTABLE',
    priorClaims: false,
    selfFunded: false,
    adverseActionDeadline: null,
    adverseActionSent: null,
    subScores: { liabilityRisk: 15, financialStability: 22, claimsHistory: 5, industryRisk: 18 },
    dataCompleteness: 0.96,
    reasoning: [
      'Finance industry is a preferred category for this carrier.',
      'Clean claims history; no prior insurance issues.',
      '$1.8M revenue for 12 employees ($150K/employee) indicates a profitable advisory firm.',
      'Small group — MA guaranteed issue applies for groups 1-50.',
    ],
    missingInfoFlags: [],
    suggestedNextSteps: ['Generate quote', 'Apply MA small group rules', 'Notify broker'],
    complianceNotes: ['MA small group GI rules apply', 'MA Div. of Insurance oversight'],
    stateOverride: null,
    additionalRiskFactors: [],
    messages: [],
    documents: [],
  },
  {
    id: 'SUB-2024-010',
    employerName: 'Springfield School District',
    industry: 'Education',
    state: 'IL',
    employeeCount: 450,
    annualRevenue: '$52M',
    yearsInBusiness: 85,
    businessEntityType: 'Government/Public',
    coverageTypes: ['Life', 'Health', 'Dental', 'Vision'],
    requestedEffectiveDate: '2024-07-01',
    brokerName: 'Linda Foster',
    brokerLicense: 'IL-BRK-88341',
    brokerEmail: 'lfoster@educationbenefits.com',
    brokerPhone: '(217) 555-1047',
    submittedAt: '2024-01-05T14:20:00Z',
    status: 'APPROVED',
    priority: 'low',
    assignedUnderwriter: 'John Doe',
    carrierId: 'carrier_001',
    riskScore: 25,
    confidenceLevel: 89,
    recommendation: 'APPROVE',
    carrierAppetiteMatch: 'ACCEPTABLE',
    priorClaims: false,
    selfFunded: false,
    adverseActionDeadline: null,
    adverseActionSent: null,
    subScores: { liabilityRisk: 20, financialStability: 28, claimsHistory: 5, industryRisk: 22 },
    dataCompleteness: 0.93,
    reasoning: [
      'Education/government sector presents very low risk profile — stable employment, strong financials.',
      'No prior claims history.',
      'Public institution with 85-year operating history — exceptional stability.',
      'Large group (450 employees) qualifies for experience rating.',
    ],
    missingInfoFlags: [],
    suggestedNextSteps: ['Generate group quote', 'Send to carrier system', 'Coordinate July 1 effective date'],
    complianceNotes: ['IL large group rules', 'IL DOI oversight for public entity plans'],
    stateOverride: null,
    additionalRiskFactors: [],
    messages: [],
    documents: [],
  },
  {
    id: 'SUB-2024-011',
    employerName: 'Northeast Hospital Group',
    industry: 'Healthcare',
    state: 'NY',
    employeeCount: 312,
    annualRevenue: '$78M',
    yearsInBusiness: 34,
    businessEntityType: 'Nonprofit',
    coverageTypes: ['Life', 'Health', 'LTC'],
    requestedEffectiveDate: '2024-04-01',
    brokerName: 'Christine Park',
    brokerLicense: 'NY-BRK-55671',
    brokerEmail: 'cpark@nycbenefits.com',
    brokerPhone: '(212) 555-0493',
    submittedAt: '2024-01-16T09:00:00Z',
    status: 'PENDING',
    priority: 'high',
    assignedUnderwriter: null,
    carrierId: 'carrier_001',
    riskScore: 33,
    confidenceLevel: 72,
    recommendation: 'APPROVE',
    carrierAppetiteMatch: 'ACCEPTABLE',
    priorClaims: true,
    claimsCount: 4,
    claimsTotal: '$312,000',
    largestClaim: '$156,000',
    claimsDescription: 'LTC and disability claims consistent with large healthcare workforce; within expected range.',
    selfFunded: false,
    adverseActionDeadline: null,
    adverseActionSent: null,
    subScores: { liabilityRisk: 35, financialStability: 30, claimsHistory: 38, industryRisk: 30 },
    dataCompleteness: 0.87,
    reasoning: [
      'NY large group (312 employees) — experience rating permitted; medical underwriting allowed.',
      'Healthcare employer with strong financial position.',
      'Claims within expected range for a group of this size and industry.',
      'NY Insurance Law Article 43 — large group rules apply.',
      'Requires senior underwriter review per carrier policy for healthcare groups over 200.',
    ],
    missingInfoFlags: ['Actuarial claims analysis', 'Prior carrier loss ratios'],
    suggestedNextSteps: ['Assign to senior underwriter', 'Request actuarial analysis', 'Apply NY large group rating rules'],
    complianceNotes: ['NY large group experience rating permitted', 'NY Insurance Law Article 43 applies'],
    stateOverride: null,
    additionalRiskFactors: ['Large healthcare workforce LTC exposure'],
    messages: [],
    documents: [],
  },
  {
    id: 'SUB-2024-012',
    employerName: 'Blue Ridge Hospitality',
    industry: 'Hospitality',
    state: 'TN',
    employeeCount: 78,
    annualRevenue: '$5.6M',
    yearsInBusiness: 6,
    businessEntityType: 'LLC',
    coverageTypes: ['Life', 'Health'],
    requestedEffectiveDate: '2024-03-01',
    brokerName: 'Tony Haskell',
    brokerLicense: 'TN-BRK-44219',
    brokerEmail: 'thaskell@southernbenefits.com',
    brokerPhone: '(615) 555-1162',
    submittedAt: '2024-01-17T10:30:00Z',
    status: 'PENDING',
    priority: 'medium',
    assignedUnderwriter: null,
    carrierId: 'carrier_001',
    riskScore: 61,
    confidenceLevel: 76,
    recommendation: 'REFER',
    carrierAppetiteMatch: 'MARGINAL',
    priorClaims: true,
    claimsCount: 2,
    claimsTotal: '$48,000',
    largestClaim: '$32,000',
    claimsDescription: 'Workers comp claims from hotel/housekeeping operations.',
    selfFunded: false,
    adverseActionDeadline: null,
    adverseActionSent: null,
    subScores: { liabilityRisk: 65, financialStability: 58, claimsHistory: 60, industryRisk: 62 },
    dataCompleteness: 0.79,
    reasoning: [
      'Hospitality classified as MARGINAL for this carrier — manual review required.',
      'Prior claims elevated relative to group size.',
      'Revenue/employee ratio ($71.8K) is below hospitality sector average, indicating margin pressure.',
    ],
    missingInfoFlags: ['Prior carrier experience data', 'Safety program details', 'Revenue breakdown by property'],
    suggestedNextSteps: ['Assign to underwriter', 'Request additional documentation'],
    complianceNotes: ['TN standard NAIC rules apply'],
    stateOverride: null,
    additionalRiskFactors: ['Hotel/motel operations', 'Food service component'],
    messages: [],
    documents: [],
  },
]

// ─── EOI Records ─────────────────────────────────────────────────────────────
export const eois = [
  {
    id: 'EOI-2024-001',
    employeeId: 'EMP-7821-KXPQ',
    employerGroup: 'TechNova Solutions',
    employerGroupId: 'SUB-2024-002',
    coverageRequested: 'Life',
    giLimit: 50000,
    coverageAmount: 350000,
    eoiAmount: 300000,
    status: 'Under Review',
    submittedAt: '2024-01-16T10:00:00Z',
    daysOpen: 2,
    assignedReviewer: 'Sarah Chen',
    dob: '**/**/1978',
    gender: 'M',
    healthAnswers: [
      { question: 'Heart disease or heart attack in the last 5 years', answer: 'No' },
      { question: 'Stroke or TIA in the last 5 years', answer: 'No' },
      { question: 'Cancer diagnosis in the last 10 years', answer: 'No' },
      { question: 'Hospitalization in the last 2 years', answer: 'No' },
      { question: 'Chronic illness requiring ongoing medication', answer: 'No' },
      { question: 'Disability preventing normal activities in last 2 years', answer: 'No' },
    ],
    aiRiskLevel: 'Low',
    aiReasoning: 'All health questions answered negatively. Standard coverage amount above GI. No elevated risk indicators.',
    medicalExamRequired: false,
    priorEOI: null,
  },
  {
    id: 'EOI-2024-002',
    employeeId: 'EMP-4432-MJRW',
    employerGroup: 'TechNova Solutions',
    employerGroupId: 'SUB-2024-002',
    coverageRequested: 'Life',
    giLimit: 50000,
    coverageAmount: 500000,
    eoiAmount: 450000,
    status: 'Pending Medical',
    submittedAt: '2024-01-15T14:30:00Z',
    daysOpen: 3,
    assignedReviewer: 'Sarah Chen',
    dob: '**/**/1965',
    gender: 'F',
    healthAnswers: [
      { question: 'Heart disease or heart attack in the last 5 years', answer: 'Yes — controlled hypertension, medicated' },
      { question: 'Stroke or TIA in the last 5 years', answer: 'No' },
      { question: 'Cancer diagnosis in the last 10 years', answer: 'No' },
      { question: 'Hospitalization in the last 2 years', answer: 'Yes — cardiac monitoring, 2023' },
      { question: 'Chronic illness requiring ongoing medication', answer: 'Yes — antihypertensive medication' },
      { question: 'Disability preventing normal activities in last 2 years', answer: 'No' },
    ],
    aiRiskLevel: 'High',
    aiReasoning: 'Multiple cardiovascular risk indicators: controlled hypertension, cardiac hospitalization in 2023. Medical exam recommended given coverage amount and health history.',
    medicalExamRequired: true,
    priorEOI: null,
  },
  {
    id: 'EOI-2024-003',
    employeeId: 'EMP-9913-BVLZ',
    employerGroup: 'Northeast Hospital Group',
    employerGroupId: 'SUB-2024-011',
    coverageRequested: 'LTC',
    giLimit: 3000,
    coverageAmount: 8000,
    eoiAmount: 5000,
    status: 'Approved',
    submittedAt: '2024-01-10T09:00:00Z',
    daysOpen: 8,
    assignedReviewer: 'John Doe',
    dob: '**/**/1970',
    gender: 'F',
    healthAnswers: [
      { question: 'Heart disease or heart attack in the last 5 years', answer: 'No' },
      { question: 'Stroke or TIA in the last 5 years', answer: 'No' },
      { question: 'Cancer diagnosis in the last 10 years', answer: 'No' },
      { question: 'Hospitalization in the last 2 years', answer: 'No' },
      { question: 'Chronic illness requiring ongoing medication', answer: 'No' },
      { question: 'ADL limitations present', answer: 'No' },
    ],
    aiRiskLevel: 'Low',
    aiReasoning: 'Clean health history. LTC coverage amount above GI but no elevated risk indicators.',
    medicalExamRequired: false,
    priorEOI: null,
  },
  {
    id: 'EOI-2024-004',
    employeeId: 'EMP-2287-TNQR',
    employerGroup: 'Springfield School District',
    employerGroupId: 'SUB-2024-010',
    coverageRequested: 'Disability',
    giLimit: 6000,
    coverageAmount: 12000,
    eoiAmount: 6000,
    status: 'Declined',
    submittedAt: '2024-01-08T11:00:00Z',
    daysOpen: 10,
    assignedReviewer: 'Sarah Chen',
    dob: '**/**/1958',
    gender: 'M',
    healthAnswers: [
      { question: 'Heart disease or heart attack in the last 5 years', answer: 'Yes — myocardial infarction 2022' },
      { question: 'Stroke or TIA in the last 5 years', answer: 'No' },
      { question: 'Cancer diagnosis in the last 10 years', answer: 'No' },
      { question: 'Hospitalization in the last 2 years', answer: 'Yes — cardiac surgery 2022' },
      { question: 'Chronic illness requiring ongoing medication', answer: 'Yes — multiple cardiac medications' },
      { question: 'Disability preventing normal activities in last 2 years', answer: 'No' },
    ],
    aiRiskLevel: 'High',
    aiReasoning: 'Recent myocardial infarction (2022) with cardiac surgery creates significant disability risk. Coverage amount is double the GI limit. Recommendation: decline EOI for requested coverage amount.',
    medicalExamRequired: false,
    priorEOI: null,
  },
  {
    id: 'EOI-2024-005',
    employeeId: 'EMP-6654-WOPX',
    employerGroup: 'Pacific Northwest Retail',
    employerGroupId: 'SUB-2024-008',
    coverageRequested: 'Life',
    giLimit: 50000,
    coverageAmount: 200000,
    eoiAmount: 150000,
    status: 'Pending Medical',
    submittedAt: '2024-01-17T08:00:00Z',
    daysOpen: 1,
    assignedReviewer: null,
    dob: '**/**/1972',
    gender: 'M',
    healthAnswers: [
      { question: 'Heart disease or heart attack in the last 5 years', answer: 'No' },
      { question: 'Stroke or TIA in the last 5 years', answer: 'No' },
      { question: 'Cancer diagnosis in the last 10 years', answer: 'Yes — prostate cancer, treated 2019, in remission' },
      { question: 'Hospitalization in the last 2 years', answer: 'No' },
      { question: 'Chronic illness requiring ongoing medication', answer: 'No' },
      { question: 'Disability preventing normal activities in last 2 years', answer: 'No' },
    ],
    aiRiskLevel: 'Medium',
    aiReasoning: 'Cancer history (prostate, 2019, in remission) is a notable risk factor. Coverage amount $150K above GI. Medical exam and current oncology clearance recommended.',
    medicalExamRequired: true,
    priorEOI: null,
  },
]

// ─── Active Enrollments ───────────────────────────────────────────────────────
export const enrollments = [
  {
    id: 'ENR-2024-001',
    groupName: 'TechNova Solutions',
    carrierId: 'carrier_001',
    employeeCount: 127,
    enrolledCount: 119,
    participationRate: 93.7,
    coverageTypes: ['Life', 'Health', 'Dental', 'Vision'],
    enrollmentStart: '2024-01-15',
    enrollmentEnd: '2024-02-15',
    effectiveDate: '2024-02-01',
    status: 'Closed',
    eoiPending: 2,
    industry: 'Technology',
  },
  {
    id: 'ENR-2024-002',
    groupName: 'Springfield School District',
    carrierId: 'carrier_001',
    employeeCount: 450,
    enrolledCount: 387,
    participationRate: 86.0,
    coverageTypes: ['Life', 'Health', 'Dental', 'Vision'],
    enrollmentStart: '2024-06-01',
    enrollmentEnd: '2024-06-30',
    effectiveDate: '2024-07-01',
    status: 'Pending Start',
    eoiPending: 8,
    industry: 'Education',
  },
  {
    id: 'ENR-2024-003',
    groupName: 'Midtown Medical Partners',
    carrierId: 'carrier_001',
    employeeCount: 23,
    enrolledCount: 21,
    participationRate: 91.3,
    coverageTypes: ['Life', 'Health'],
    enrollmentStart: '2024-01-25',
    enrollmentEnd: '2024-02-10',
    effectiveDate: '2024-02-15',
    status: 'Open',
    eoiPending: 0,
    industry: 'Healthcare',
  },
  {
    id: 'ENR-2024-004',
    groupName: 'Pacific Northwest Retail',
    carrierId: 'carrier_001',
    employeeCount: 234,
    enrolledCount: 156,
    participationRate: 66.7,
    coverageTypes: ['Life', 'Health', 'Dental'],
    enrollmentStart: '2024-03-01',
    enrollmentEnd: '2024-03-31',
    effectiveDate: '2024-04-01',
    status: 'Open',
    eoiPending: 5,
    industry: 'Retail',
  },
  {
    id: 'ENR-2024-005',
    groupName: 'Premier Legal Group',
    carrierId: 'carrier_001',
    employeeCount: 18,
    enrolledCount: 10,
    participationRate: 55.6,
    coverageTypes: ['Life', 'Health', 'Disability'],
    enrollmentStart: '2024-01-20',
    enrollmentEnd: '2024-02-05',
    effectiveDate: '2024-02-01',
    status: 'Processing',
    eoiPending: 1,
    industry: 'Legal',
  },
]

// ─── Audit Log ────────────────────────────────────────────────────────────────
export const auditLog = [
  {
    id: 'AUD-001',
    timestamp: '2024-01-17T10:30:00Z',
    eventType: 'Submission Created',
    submissionId: 'SUB-2024-012',
    employer: 'Blue Ridge Hospitality',
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: 'a3f7e921',
    riskScore: 61,
    aiRecommendation: 'REFER',
    confidenceLevel: 76,
    humanOverride: false,
    finalDecision: 'PENDING',
    decidedBy: 'System',
    notes: 'Submission received via broker portal.',
  },
  {
    id: 'AUD-002',
    timestamp: '2024-01-16T09:00:00Z',
    eventType: 'Submission Created',
    submissionId: 'SUB-2024-011',
    employer: 'Northeast Hospital Group',
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: 'b8d2c4f1',
    riskScore: 33,
    aiRecommendation: 'APPROVE',
    confidenceLevel: 72,
    humanOverride: false,
    finalDecision: 'PENDING',
    decidedBy: 'System',
    notes: 'Large healthcare group — senior underwriter review required per carrier policy.',
  },
  {
    id: 'AUD-003',
    timestamp: '2024-01-15T09:23:00Z',
    eventType: 'AI Decision',
    submissionId: 'SUB-2024-001',
    employer: 'Riverside Restaurant Group',
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: 'c1a9b3e7',
    riskScore: 72,
    aiRecommendation: 'DECLINE',
    confidenceLevel: 82,
    humanOverride: false,
    finalDecision: 'DECLINED',
    decidedBy: 'Sarah Chen',
    notes: 'Carrier appetite flag: Restaurant industry outside appetite. Auto-declined.',
  },
  {
    id: 'AUD-004',
    timestamp: '2024-01-14T14:05:00Z',
    eventType: 'AI Decision',
    submissionId: 'SUB-2024-002',
    employer: 'TechNova Solutions',
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: 'd4f6a2c8',
    riskScore: 28,
    aiRecommendation: 'APPROVE',
    confidenceLevel: 91,
    humanOverride: false,
    finalDecision: 'APPROVED',
    decidedBy: 'John Doe',
    notes: 'AI recommendation accepted. All criteria met.',
  },
  {
    id: 'AUD-005',
    timestamp: '2024-01-14T15:00:00Z',
    eventType: 'EOI Action',
    submissionId: 'EOI-2024-001',
    employer: 'TechNova Solutions',
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: 'e2b5d9f3',
    riskScore: null,
    aiRecommendation: 'APPROVE_EOI',
    confidenceLevel: 88,
    humanOverride: false,
    finalDecision: 'Under Review',
    decidedBy: 'Sarah Chen',
    notes: 'EOI submitted. Under review. PHI access logged per HIPAA.',
  },
  {
    id: 'AUD-006',
    timestamp: '2024-01-13T11:30:00Z',
    eventType: 'AI Decision',
    submissionId: 'SUB-2024-003',
    employer: 'Great Lakes Manufacturing',
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: 'f3c7a1d5',
    riskScore: 55,
    aiRecommendation: 'REFER',
    confidenceLevel: 74,
    humanOverride: false,
    finalDecision: 'REFERRED',
    decidedBy: 'Sarah Chen',
    notes: 'Referred pending OSHA documentation.',
  },
  {
    id: 'AUD-007',
    timestamp: '2024-01-12T10:00:00Z',
    eventType: 'AI Decision',
    submissionId: 'SUB-2024-004',
    employer: 'Midtown Medical Partners',
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: 'g8e2b4c6',
    riskScore: 31,
    aiRecommendation: 'APPROVE',
    confidenceLevel: 88,
    humanOverride: false,
    finalDecision: 'APPROVED',
    decidedBy: 'John Doe',
    notes: 'NY small group GI rules applied. Pure community rating.',
  },
  {
    id: 'AUD-008',
    timestamp: '2024-01-11T16:45:00Z',
    eventType: 'AI Decision',
    submissionId: 'SUB-2024-005',
    employer: 'Sunrise Home Health',
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: 'h1d9f3e7',
    riskScore: 44,
    aiRecommendation: 'REFER',
    confidenceLevel: 58,
    humanOverride: false,
    finalDecision: 'REFERRED',
    decidedBy: 'System (Low Confidence Auto-Route)',
    notes: 'AI confidence 58% — below 60% threshold. Automatically routed to human review.',
  },
  {
    id: 'AUD-009',
    timestamp: '2024-01-09T14:30:00Z',
    eventType: 'Compliance Override',
    submissionId: 'SUB-2024-007',
    employer: 'Metro Construction LLC',
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: 'i5a3c1b8',
    riskScore: 78,
    aiRecommendation: 'DECLINE',
    confidenceLevel: 88,
    humanOverride: false,
    finalDecision: 'DECLINED',
    decidedBy: 'Sarah Chen',
    notes: 'Carrier appetite: Construction outside appetite. Adverse action notice sent 2024-01-19.',
  },
  {
    id: 'AUD-010',
    timestamp: '2024-01-08T11:00:00Z',
    eventType: 'EOI Action',
    submissionId: 'EOI-2024-004',
    employer: 'Springfield School District',
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: 'j7f2d4a9',
    riskScore: null,
    aiRecommendation: 'DECLINE_EOI',
    confidenceLevel: 91,
    humanOverride: false,
    finalDecision: 'Declined',
    decidedBy: 'Sarah Chen',
    notes: 'EOI declined due to recent cardiac event. PHI decision logged. Employee notified per HIPAA.',
  },
  {
    id: 'AUD-011',
    timestamp: '2024-01-07T11:00:00Z',
    eventType: 'AI Decision',
    submissionId: 'SUB-2024-009',
    employer: 'First Financial Advisors',
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: 'k2b8e5f1',
    riskScore: 19,
    aiRecommendation: 'APPROVE',
    confidenceLevel: 95,
    humanOverride: false,
    finalDecision: 'APPROVED',
    decidedBy: 'John Doe',
    notes: 'High-confidence approval. Finance sector preferred.',
  },
  {
    id: 'AUD-012',
    timestamp: '2024-01-05T14:20:00Z',
    eventType: 'Human Override',
    submissionId: 'SUB-2024-010',
    employer: 'Springfield School District',
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: 'l9c4a7d2',
    riskScore: 25,
    aiRecommendation: 'APPROVE',
    confidenceLevel: 89,
    humanOverride: false,
    finalDecision: 'APPROVED',
    decidedBy: 'John Doe',
    notes: 'AI recommendation accepted without override.',
  },
  {
    id: 'AUD-013',
    timestamp: '2024-01-04T10:00:00Z',
    eventType: 'System Event',
    submissionId: null,
    employer: null,
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: null,
    riskScore: null,
    aiRecommendation: null,
    confidenceLevel: null,
    humanOverride: false,
    finalDecision: null,
    decidedBy: 'System',
    notes: 'Carrier configuration updated: Acme Life custom underwriting rules modified by admin.',
  },
  {
    id: 'AUD-014',
    timestamp: '2024-01-03T09:00:00Z',
    eventType: 'System Event',
    submissionId: null,
    employer: null,
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: null,
    riskScore: null,
    aiRecommendation: null,
    confidenceLevel: null,
    humanOverride: false,
    finalDecision: null,
    decidedBy: 'System',
    notes: 'State rules database updated: NY 2024 small group threshold updated to 100 employees.',
  },
  {
    id: 'AUD-015',
    timestamp: '2024-01-02T15:30:00Z',
    eventType: 'Human Override',
    submissionId: 'SUB-2023-098',
    employer: 'Valley Tech Partners',
    modelVersion: 'claude-sonnet-4-20250514',
    inputHash: 'm3d6f8c1',
    riskScore: 42,
    aiRecommendation: 'REFER',
    confidenceLevel: 83,
    humanOverride: true,
    finalDecision: 'APPROVED',
    decidedBy: 'John Doe',
    notes: 'Senior underwriter override: REFER → APPROVE. Reason: long-standing client, additional documentation reviewed offline.',
  },
]

// ─── State Rules ──────────────────────────────────────────────────────────────
export const stateRules = {
  CA: {
    stateName: 'California',
    abbreviation: 'CA',
    smallGroupLimit: 100,
    guaranteedIssue: true,
    guaranteedIssueUpTo: 100,
    communityRatingRequired: true,
    autoDeclinePermitted: false,
    autoDeclineConditions: 'Auto-decline NOT permitted for small groups (1-100). Large groups (101+) may use experience rating.',
    prohibitedRiskFactors: ['credit score', 'genetic information', 'prior carrier cancellation', 'health status (small group)'],
    adverseActionNoticeDays: 5,
    adverseActionNoticeFormat: 'Cal_Standard',
    adverseActionRequiredLanguage: 'Must include Cal. Insurance Code citation, specific reasons, appeal rights, and CDI contact information.',
    regulatoryReference: 'California Insurance Code Sections 10700–10755; Cal. Health & Safety Code § 1357.500',
    specialRequirements: [
      'Mandatory continuance offer: 60 days if policy nonrenewed or cancelled',
      'Spanish translation required for groups with 25%+ Spanish-speaking employees',
      'Community rating: premiums for small groups cannot vary by health status',
      'Large groups (101+): experience rating and medical underwriting permitted',
    ],
    continuanceRequired: true,
    continuanceDays: 60,
    filingRequirements: 'Annual rate filings required with CA Department of Insurance',
    insuranceDepartmentName: 'California Department of Insurance',
    insuranceDepartmentWebsite: 'https://www.insurance.ca.gov',
  },
  NY: {
    stateName: 'New York',
    abbreviation: 'NY',
    smallGroupLimit: 100,
    guaranteedIssue: true,
    guaranteedIssueUpTo: 100,
    communityRatingRequired: true,
    autoDeclinePermitted: false,
    autoDeclineConditions: 'Auto-decline NOT permitted for small groups (1-100 employees as of 2024). Pure community rating required.',
    prohibitedRiskFactors: ['health status (small group)', 'claims experience (small group)', 'genetic information', 'credit history'],
    adverseActionNoticeDays: 3,
    adverseActionNoticeFormat: 'NY_Standard',
    adverseActionRequiredLanguage: 'Notice within 3 business days; must state specific reason for adverse action and include NYDFS contact.',
    regulatoryReference: 'NY Insurance Law Article 43; NY Public Health Law Article 43-A; 11 NYCRR Part 360',
    specialRequirements: [
      'Pure community rating: premiums cannot vary by health status for small groups',
      'Guaranteed issue: all small groups must be accepted',
      'Large groups (101+): experience rating permitted',
      'Fair Health determination required for out-of-network benefit levels',
    ],
    continuanceRequired: false,
    continuanceDays: null,
    filingRequirements: 'Rate filings required with NYDFS; prior approval for rate changes',
    insuranceDepartmentName: 'New York Department of Financial Services',
    insuranceDepartmentWebsite: 'https://www.dfs.ny.gov',
  },
  IL: {
    stateName: 'Illinois',
    abbreviation: 'IL',
    smallGroupLimit: 50,
    guaranteedIssue: true,
    guaranteedIssueUpTo: 50,
    communityRatingRequired: false,
    autoDeclinePermitted: true,
    autoDeclineConditions: 'Permitted for groups over 50. Groups 2-50 are guaranteed issue.',
    prohibitedRiskFactors: ['genetic information', 'HIV status'],
    adverseActionNoticeDays: 5,
    adverseActionNoticeFormat: 'IL_DOI_Standard',
    adverseActionRequiredLanguage: 'Must use Illinois DOI standard form. Groups over 50 must file notice copy with IL DOI.',
    regulatoryReference: '215 ILCS 5/357.10; 215 ILCS 97 (Illinois Health Insurance Portability and Renewability Act)',
    specialRequirements: [
      'Groups over 50: adverse action notices must be filed with IL DOI',
      'COBRA continuation applies for groups with 20+ employees',
    ],
    continuanceRequired: false,
    continuanceDays: null,
    filingRequirements: 'Large group adverse action notices must be filed with IL Department of Insurance',
    insuranceDepartmentName: 'Illinois Department of Insurance',
    insuranceDepartmentWebsite: 'https://insurance.illinois.gov',
  },
  TX: {
    stateName: 'Texas',
    abbreviation: 'TX',
    smallGroupLimit: 50,
    guaranteedIssue: true,
    guaranteedIssueUpTo: 50,
    communityRatingRequired: false,
    autoDeclinePermitted: true,
    autoDeclineConditions: 'Permitted for groups over 50. Small groups (2-50) are guaranteed issue under TX Insurance Code.',
    prohibitedRiskFactors: ['genetic information'],
    adverseActionNoticeDays: 10,
    adverseActionNoticeFormat: 'NAIC_Standard',
    adverseActionRequiredLanguage: 'NAIC model notice language; include TDI contact information.',
    regulatoryReference: 'TX Insurance Code Chapter 1501; TX Admin. Code Title 28, Part 1, Chapter 26',
    specialRequirements: ['HIPAA portability requirements', 'TDI market conduct oversight'],
    continuanceRequired: false,
    continuanceDays: null,
    filingRequirements: 'Standard TDI rate filings',
    insuranceDepartmentName: 'Texas Department of Insurance',
    insuranceDepartmentWebsite: 'https://www.tdi.texas.gov',
  },
  FL: {
    stateName: 'Florida',
    abbreviation: 'FL',
    smallGroupLimit: 50,
    guaranteedIssue: true,
    guaranteedIssueUpTo: 50,
    communityRatingRequired: false,
    autoDeclinePermitted: true,
    autoDeclineConditions: 'Permitted for groups over 50. Small groups guaranteed issue.',
    prohibitedRiskFactors: ['genetic information', 'HIV/AIDS status'],
    adverseActionNoticeDays: 10,
    adverseActionNoticeFormat: 'NAIC_Standard',
    adverseActionRequiredLanguage: 'NAIC model language; include OIR contact.',
    regulatoryReference: 'FL Statute Chapter 627 Part VIII; FL Admin. Code 69O-149',
    specialRequirements: ['HIPAA compliance required', 'Florida Hurricane Cat Fund not applicable to health lines'],
    continuanceRequired: false,
    continuanceDays: null,
    filingRequirements: 'Rate filings with FL Office of Insurance Regulation',
    insuranceDepartmentName: 'Florida Office of Insurance Regulation',
    insuranceDepartmentWebsite: 'https://www.floir.com',
  },
  WA: {
    stateName: 'Washington',
    abbreviation: 'WA',
    smallGroupLimit: 50,
    guaranteedIssue: true,
    guaranteedIssueUpTo: 50,
    communityRatingRequired: true,
    autoDeclinePermitted: false,
    autoDeclineConditions: 'Auto-decline NOT permitted for small groups (1-50). Community rating required.',
    prohibitedRiskFactors: ['health status (small group)', 'genetic information', 'credit score'],
    adverseActionNoticeDays: 5,
    adverseActionNoticeFormat: 'WA_OIC_Standard',
    adverseActionRequiredLanguage: 'WA OIC notice format; include OIC complaint process.',
    regulatoryReference: 'RCW 48.43; WAC 284-170',
    specialRequirements: [
      'Community rating for small groups — health status rating prohibited',
      'WA Healthplanfinder coordination for ACA-compliant plans',
    ],
    continuanceRequired: false,
    continuanceDays: null,
    filingRequirements: 'Rate filings required with WA Office of Insurance Commissioner',
    insuranceDepartmentName: 'Washington Office of the Insurance Commissioner',
    insuranceDepartmentWebsite: 'https://www.insurance.wa.gov',
  },
  MA: {
    stateName: 'Massachusetts',
    abbreviation: 'MA',
    smallGroupLimit: 50,
    guaranteedIssue: true,
    guaranteedIssueUpTo: 50,
    communityRatingRequired: true,
    autoDeclinePermitted: false,
    autoDeclineConditions: 'Auto-decline prohibited for small groups. Community rating and GI required.',
    prohibitedRiskFactors: ['health status', 'claims experience', 'genetic information', 'gender (for some products)'],
    adverseActionNoticeDays: 5,
    adverseActionNoticeFormat: 'MA_DOI_Standard',
    adverseActionRequiredLanguage: 'Must comply with MA M.G.L. c.176J; include MDOI contact.',
    regulatoryReference: 'M.G.L. c.176J (Small Group); 211 CMR 66',
    specialRequirements: [
      'MA mandate: minimum creditable coverage requirements',
      'MA connector authority coordination',
      'Adjusted community rating — age and geography only rating factors',
    ],
    continuanceRequired: false,
    continuanceDays: null,
    filingRequirements: 'Rate filings with MA Division of Insurance',
    insuranceDepartmentName: 'Massachusetts Division of Insurance',
    insuranceDepartmentWebsite: 'https://www.mass.gov/orgs/division-of-insurance',
  },
  NJ: {
    stateName: 'New Jersey',
    abbreviation: 'NJ',
    smallGroupLimit: 50,
    guaranteedIssue: true,
    guaranteedIssueUpTo: 50,
    communityRatingRequired: true,
    autoDeclinePermitted: false,
    autoDeclineConditions: 'Auto-decline prohibited for small groups (2-50). Community rating required.',
    prohibitedRiskFactors: ['health status', 'claims history (small group)', 'genetic information'],
    adverseActionNoticeDays: 5,
    adverseActionNoticeFormat: 'NAIC_Standard',
    adverseActionRequiredLanguage: 'NAIC model language; include NJ DOBI contact.',
    regulatoryReference: 'N.J.S.A. 17B:27A-17 through 17B:27A-41; N.J.A.C. 11:21',
    specialRequirements: [
      'Community rating: 4 permitted rating factors only (age, geography, family composition, tobacco)',
      'NJ Individual Health Coverage Program coordination',
    ],
    continuanceRequired: false,
    continuanceDays: null,
    filingRequirements: 'Rate filings with NJ Department of Banking and Insurance',
    insuranceDepartmentName: 'New Jersey Department of Banking and Insurance',
    insuranceDepartmentWebsite: 'https://www.state.nj.us/dobi',
  },
  PA: {
    stateName: 'Pennsylvania',
    abbreviation: 'PA',
    smallGroupLimit: 50,
    guaranteedIssue: true,
    guaranteedIssueUpTo: 50,
    communityRatingRequired: false,
    autoDeclinePermitted: true,
    autoDeclineConditions: 'Permitted for large groups. Small groups (2-50) guaranteed issue.',
    prohibitedRiskFactors: ['genetic information', 'HIV status'],
    adverseActionNoticeDays: 10,
    adverseActionNoticeFormat: 'NAIC_Standard',
    adverseActionRequiredLanguage: 'NAIC model language; include PA Insurance Department contact.',
    regulatoryReference: '40 P.S. § 764h; 31 Pa. Code Chapter 89',
    specialRequirements: ['HIPAA portability', 'Pennsylvania Act 68 managed care requirements'],
    continuanceRequired: false,
    continuanceDays: null,
    filingRequirements: 'Standard PA Insurance Department filings',
    insuranceDepartmentName: 'Pennsylvania Insurance Department',
    insuranceDepartmentWebsite: 'https://www.insurance.pa.gov',
  },
  GA: {
    stateName: 'Georgia',
    abbreviation: 'GA',
    smallGroupLimit: 50,
    guaranteedIssue: true,
    guaranteedIssueUpTo: 50,
    communityRatingRequired: false,
    autoDeclinePermitted: true,
    autoDeclineConditions: 'Permitted for large groups (51+). Small groups guaranteed issue.',
    prohibitedRiskFactors: ['genetic information'],
    adverseActionNoticeDays: 10,
    adverseActionNoticeFormat: 'NAIC_Standard',
    adverseActionRequiredLanguage: 'NAIC model language; include GA OCI contact.',
    regulatoryReference: 'O.C.G.A. § 33-29A; Ga. Comp. R. & Regs. 120-2-79',
    specialRequirements: ['HIPAA compliance', 'Georgia Association Health Plan rules'],
    continuanceRequired: false,
    continuanceDays: null,
    filingRequirements: 'Rate filings with GA Office of Insurance and Safety Fire Commissioner',
    insuranceDepartmentName: 'Georgia Office of Insurance and Safety Fire Commissioner',
    insuranceDepartmentWebsite: 'https://oci.georgia.gov',
  },
  // Default NAIC rules for all other states
  DEFAULT: {
    stateName: null,
    smallGroupLimit: 50,
    guaranteedIssue: true,
    guaranteedIssueUpTo: 50,
    communityRatingRequired: false,
    autoDeclinePermitted: true,
    autoDeclineConditions: 'Permitted for large groups (51+). NAIC model rules apply.',
    prohibitedRiskFactors: ['genetic information'],
    adverseActionNoticeDays: 10,
    adverseActionNoticeFormat: 'NAIC_Standard',
    adverseActionRequiredLanguage: 'NAIC model adverse action notice language with state insurance department contact.',
    regulatoryReference: 'NAIC Model Small Group Rating Act; HIPAA',
    specialRequirements: ['HIPAA portability requirements apply'],
    continuanceRequired: false,
    continuanceDays: null,
    filingRequirements: 'Standard state insurance department rate filings',
    insuranceDepartmentName: 'State Department of Insurance',
    insuranceDepartmentWebsite: null,
  },
}

// Helper to get rules for any state (falls back to DEFAULT)
export function getStateRules(stateAbbr) {
  return stateRules[stateAbbr] || { ...stateRules.DEFAULT, stateName: stateAbbr, abbreviation: stateAbbr }
}
